name: Deploy to CAM SFTP

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./  # change to _site or dist/ if needed
          remote_path: ${{ secrets.SFTP_TARGET_DIR }}
          remote_host: ${{ secrets.SFTP_HOST }}
          remote_user: ${{ secrets.SFTP_USER }}
          remote_port: ${{ secrets.SFTP_PORT }}
          remote_key: ""  # blank if using password
        env:
          DEPLOY_KEY: ${{ secrets.SFTP_PASSWORD }}
