name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main  # or the branch you want to trigger deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SFTP Deploy
      uses: pressidium/lftp-deploy@v1.3.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT || '22' }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./  # change to your build/output dir if needed
        remoteDir: ${{ secrets.SFTP_TARGET_DIR }}
        mirrorArgs: "--reverse --delete --verbose"
